### ISSUE TITLE
BUILD_PATH in the repository not found

### ISSUE THREAD

**Issue by ChristophDietrich** [opspresso/action-docker#10]
When I place the BUILD_PATH with my subfolder off my repo, the docker build didn't find the Dockerfile in this subfolder, because the BUILD_PATH will placed in the wrong way ...

`docker build  -t docker.pkg.github.com/USER/REPO/IMAGE:v0.0.1 ./subfolder_1/subfolder_2 -f Dockerfile` 

It should be

`docker build  -t docker.pkg.github.com/USER/REPO/IMAGE:v0.0.1 -f ./subfolder_1/subfolder_2 Dockerfile` 

Can you test this and make a example for this please.

Thank you very much.

**Comment by nalbam** [comment]
Thank you.
The build command was changed.

```
docker build -f Dockerfile .
```

https://github.com/opspresso/action-docker/commit/3a3e0f004c161ff1de7d9470c253c1c33c8122ce

https://docs.docker.com/engine/reference/commandline/build/#specify-a-dockerfile--f

**Comment by nalbam** [comment]
plz see
https://github.com/nalbam/sample-node/runs/655359527?check_suite_focus=true
