### ISSUE TITLE
'latet' instead of 'latest'

### ISSUE THREAD

**Issue by jpomykala** [opspresso/action-docker#4]
Hey I'm getting 'latet' docker tag instead of 'latest'  
![Screenshot 2020-02-09 at 00 09 19](https://user-images.githubusercontent.com/1548104/74093302-6bc5ce80-4ad0-11ea-86cd-c69959f492d6.png)

**Comment by nalbam** [comment]
Oh. I am sorry. 
I added code to fix the bug.
Thank you. :)

https://github.com/opspresso/action-docker/commit/a3d8f33ceea1eaee157a656bcab30a71adaafab5
